
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: boardgame-api-deploy
  labels:
    app: boardgame-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boardgame-api
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: boardgame-api
        tier: backend
    spec:
      containers:
      - name: boardgame-api
        image: ceemeese/boardgame-api
        ports:
        - containerPort: 8080
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SESSION_TOKEN 
