apiVersion: v1
kind: Service
metadata:
  name: boardgame-api-svc
  labels:
    app: boardgame-api
spec:
  ports:
    - port: 80 #lo que se expone al exterior
      targetPort: 8080 #hacia el contenedor
  selector:
    app: boardgame-api
    tier: backend
  type: LoadBalancer